# Guided Exploration

## Thermoelectric Generator (TEG)

To start, we'll be looking at a thermoelectric generator (heat engine). In other words, we will look at how much electrical energy (power) is produced from the thermoelectric device at varying temperature differences of $T_{H}$ and $T_{C}$.

Connect the Thermostat water bath to the TEG device, making sure that the black covering (on the TEG) is flush with the metal water container as to not leak water. Place both thermometers into the designated $T_{H}$ and $T_{C}$ holes (add thermo-paste into the hole for better thermal contact). Then connect a voltmeter (in parallel) and an ammeter (in series). Turn on the thermostat (hot reservoir) and allow for water to be pumped into the TEG. Also turn on the water pump in the large barrel. Both the cold reservoir (from the water barrel) and hot reservoir (thermostat bath) should be at room temperature to start. Note, if any, electrical energy is being produced from the TEG at $\Delta T \approx 0$.

Let's first find the Seebeck coefficient. To do this, we will need to run our circuit **without** a load resistor. This circuit has approximately zero resistance.

::: {.callout-note icon="false"}
## Task 1
Measure the no-load voltage and short-circuit current of the circuit (without a load resistor) at varying temperature differences up to $T_{H} = 60{^\circ}C$. Find the Seebeck coefficient of the semiconductor combination (Hint: there are 142 thermocouple elements connected in series within the device). You must include uncertainty propagation and an evaluation of your result. After plotting the measurements, what does this relationship tell us about the internal resistance of the TEG device? (Hint: consider Ohm's law).
:::

Next, we will connect the rheostat (load resistor) with resistance $R$ to the TEG (or the breadboard if you're comfortable with it). Our goal here is to find the value of the internal resistance of the TEG device. The thermostat temperature should still be at $60{^\circ}$C from the previous task. While not necessary for this part, it is a good idea to know what resistance your rheostat is set to at each measurement. However, we will only be measuring current and voltage here.

::: {.callout-note icon="false"}
## Task 2
Measure the voltage and current of the circuit at a constant temperature difference (record your error/uncertainty) at different load resistances. Find the maximum Seebeck voltage $V(I = 0)$, available at this temperature difference and the short circuit current $I_{s}(V = 0)$, as well as the internal resistance of the TEG device. Propagate your uncertainties.
:::

Finally, we will be calculating the heat $\dot{Q}_{H}$ flowing through the generator in unit time according to $\frac{dQ}{dt} = \dot{Q}_{H} = m_{w}c_{w}\left( \frac{d\Delta T}{dt} \right)$. And we'll also calculate the electrical power, measured at constant load, $W$. You will need to estimate the mass of the water $m_{w}$ in the container.

::: {.callout-note icon="false"}
## Task 3
Set the Rheostat resistance to equal the internal resistance of the TEG device (you found in Task 2). Record the temperature of both sides of the TEG device over time as you go from $60{^\circ}C$ to $80{^\circ}C$. Then turn off the thermostat heat bath and continue recording the temperature for the next 10-15 minutes as it cools. Record the current and voltage output at each increment too. Find the maximum efficiency $\eta^{*}$.
:::

Summary: We've observed how a thermoelectric device has operated as a heat engine. We've calculated the Seebeck Coefficient, the internal resistance of the TEG device, and used it to find the maximum efficiency of the device. We should know what properties a TEG device should have to run at an optimal level and what its drawbacks are.

## Thermoelectric Cooler (TEC)

First, let's figure out which way we need to pass the current through the TEC to make it cool the correct side. Fix the water container with the hole in the top (for the heating coil) instead of the thermostat container. Fill it with room temperature water. Connect the TEC device to the power supply through the DC side. Turn it on. You should now see on the thermometers which side is heating up and which side is cooling down. Swap the positive/negative cables to make the heating-coil side cool down.

Now add the heating coil ($R_{coil} \approx 3\Omega$) to the water container. Make sure it is submerged in the water and not touching the sides before turning it on. It must be connected to the AC and not higher than 3.5 A of current.

Our goal is to calculate the cooling capacity $\dot{Q}_{C}$. A nifty way to do this is to match the cooling capacity with the heating of the coil. This means that the cooling effect of the Peltier is balancing out the heating of the coil. Hence, the temperature of both sides shouldn't change.

::: {.callout-note icon="false"}
## Task 4
Match the heating output of the heating coil with the cooling output of the TEC at multiple TEC current inputs, i.e., set the input DC current of the cooling device; match the heating coil input to achieve zero temperature difference by changing the resistance of the rheostat. Measure the heater current and voltage, the operating current and voltage, and the temperatures $T_{H}$ and $T_{C}$. Find the COP $\phi$ at multiple input DC currents.
:::

::: {.callout-warning}
## Note
Students should check their progress with their tutors before proceeding any further.
:::